Bugfix/dg/ae 2683 undefined errors (#496)
* AE-2683 Fix bug in _adjust_track

2019-09-17 06:23:31,261 - ERROR - analysis.ProcessFlightTask - Cleanup due to task failure
Traceback (most recent call last):
  File "/polaris/PolarisTaskManagement/polaris_tasks/polaris_task.py", line 115, in run
    result = self.action(*args, **kwargs)
  File "/polaris/PolarisTaskManagement/polaris_tasks/analysis_tasks.py", line 813, in action
    result = process_flight(*args, **kwargs)
  File "/polaris/FlightDataAnalyzer/analysis_engine/process_flight.py", line 666, in process_flight
    derive_parameters(hdf, node_mgr, process_order, params=initial, force=force)
  File "/polaris/FlightDataAnalyzer/analysis_engine/process_flight.py", line 198, in derive_parameters
    node = node.get_derived(deps)
  File "/polaris/FlightDataAnalyzer/analysis_engine/node.py", line 449, in get_derived
    res = self.derive(*args)
  File "/polaris/FlightDataAnalyzer/analysis_engine/derived_parameters.py", line 5316, in derive
    approaches, mobile, precision, ac_type)
  File "/polaris/FlightDataAnalyzer/analysis_engine/derived_parameters.py", line 5002, in _adjust_track
    start_locn_default['longitude'])
  File "/polaris/FlightDataAnalyzer/analysis_engine/library.py", line 603, in bearing_and_distance
    {'latitude':lat1, 'longitude':lon1})
  File "/polaris/FlightDataAnalyzer/analysis_engine/library.py", line 632, in bearings_and_distances
    lat_ref = radians(reference['latitude'])
TypeError: must be real number, not NoneType

* AE-2683 Fix bug related to missing Liftoff or Landing coordinates

2019-11-02 20:04:39,277 - INFO - analysis.ProcessFlightTask - Processing flight from HDF file /var/local/SIA_VIRTUAL_9V-SFO_20191102194242_00_TDWGL__9VSFO_01NOV19_7596zip__RAWDAT.dat.003.hdf5 for aircraft {'Tail Number': '9V-SFO', 'Fleet Code': 'SQC-B747', 'Identifier': '', 'Manufacturer Serial Number': '32900', 'Manufacturer': 'Boeing', 'Family': 'B747', 'Series': 'B747-400', 'Model': 'B747-412F(SCD)', 'Aircraft Type': 'aeroplane', 'Frame': '747-400-A0107', 'Frame Name': '747-400-A0107', 'Frame Doubled': False, 'Frame Type': '717', 'Data Source': 'FDR', 'Data Rate': 256, 'Data Type': '717', 'Payload': None, 'Precise Positioning': False, 'Processing Format': '', 'Recorder Name': 'SIA_TDWGL', 'Stretched': '', 'QAR Serial Number': '', 'Main Gear To Radio Altimeter Antenna': None, 'Main Gear To Lowest Point Of Tail': 11.62, 'Ground To Lowest Point Of Tail': 2.576, 'Dry Operating Weight': None, 'Engine Count': 4, 'Engine Series': 'PW4000-94', 'Engine Manufacturer': 'Pratt & Whitney', 'Engine Type': 'PW4056', 'Engine Propulsion': 'JET', 'Modifications': [], 'Maximum Takeoff Weight': None, 'Maximum Landing Weight': None}
2019-11-02 20:04:39,349 - INFO - analysis.ProcessFlightTask - Analysis Engine Version: 19.297.1142
2019-11-02 20:05:07,701 - ERROR - analysis.ProcessFlightTask - Cleanup due to task failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/polaris_tasks/polaris_task.py", line 116, in run
    result = self.action(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/polaris_tasks/analysis_tasks.py", line 759, in action
    result = process_flight(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/analysis_engine/process_flight.py", line 666, in process_flight
    derive_parameters(hdf, node_mgr, process_order, params=initial, force=force)
  File "/usr/local/lib/python3.7/site-packages/analysis_engine/process_flight.py", line 198, in derive_parameters
    node = node.get_derived(deps)
  File "/usr/local/lib/python3.7/site-packages/analysis_engine/node.py", line 450, in get_derived
    res = self.derive(*args)
  File "/usr/local/lib/python3.7/site-packages/analysis_engine/derived_parameters.py", line 5975, in derive
    lat_land.get_last().value, lon_land.get_last().value,
AttributeError: 'NoneType' object has no attribute 'value'

* AE-2683 Fix bug rounding MaskedConstant

2019-10-28 00:08:37,667 - ERROR - analysis.ProcessFlightTask - Cleanup due to task failure
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/polaris_tasks/polaris_task.py", line 116, in run
    result = self.action(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/polaris_tasks/analysis_tasks.py", line 759, in action
    result = process_flight(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/analysis_engine/process_flight.py", line 666, in process_flight
    derive_parameters(hdf, node_mgr, process_order, params=initial, force=force)
  File "/usr/local/lib/python3.7/site-packages/analysis_engine/process_flight.py", line 198, in derive_parameters
    node = node.get_derived(deps)
  File "/usr/local/lib/python3.7/site-packages/analysis_engine/node.py", line 450, in get_derived
    res = self.derive(*args)
  File "/usr/local/lib/python3.7/site-packages/analysis_engine/key_point_values.py", line 6271, in derive
    nearest_1000ft = round(avg_alt, -3)
TypeError: type MaskedConstant doesn't define __round__ method

* AE-2683 Add unittests for LongitudePrepared and LatitudePrepared

* AE-2683 Use mock from standard lib instead of external package.

Mock is part of the standard library since Python 3.3